models:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    
  lightgbm:
    objective: "regression"
    metric: "mse"
    num_leaves: 31
    learning_rate: 0.05
    feature_fraction: 0.9
    bagging_fraction: 0.8
    bagging_freq: 5
    verbose: -1

data:
  test_size: 0.2
  random_state: 42
  
mlflow:
  experiment_name: "wine_quality"
  tracking_uri: "http://mlflow:5000"

dvc:
  models_path: "/opt/airflow/project/models"
  data_path: "/opt/airflow/project/data/raw/winequality-red.csv" 